language: node_js
node_js:
  - '10.15.3'

jobs:
  include:
    # security checks
    - script:
      # the `audit-level` is at `moderate` to avoid https://www.npmjs.com/advisories/836, at time of writing
      # consider swapping from `moderate` to `low` whenever this is possible and / reasonable
      - npm audit --audit-level=moderate
    # type checks
    - script:
      - npm run flow
    # linters
    - script:
        - npm run prettier
    # build check
    - script:
        - npm run build
