language: node_js
node_js:
  - '10.15.3'

script:
  # the `audit-level` is at `moderate` to avoid https://www.npmjs.com/advisories/836, at time of writing
  # consider swapping from `moderate` to `low` whenever this is possible and / reasonable
  - npm audit --audit-level=moderate
  - npm run flow
  - npm run prettier
  - npm run build
