language: node_js
node_js:
  - '10.15.3'

jobs:
  include:
    - stage: test
      script:
        - npm run audit
    - stage: test
      script:
        - npm run flow
    - stage: test
      script:
        - npm run prettier
    - stage: test
      script:
        - npm run build
