language: node_js
node_js:
  - '10.15.3'

jobs:
  include:
    - stage: test package security
      script:
        - npm run audit
    - stage: test types
      script:
        - npm run flow
    - stage: test linter
      script:
        - npm run prettier
    - stage: test build
      script:
        - npm run build
