backend:
  name: git-gateway
  repo: writespeakcode/writespeakcode.com

media_folder: static/images
public_folder: /images

site_url: https://writespeakcode.netlify.com
logo_url: https://raw.githubusercontent.com/WriteSpeakCode/writespeakcode.com/master/src/images/logos/wsc-logo-fullcolor.png

publish_mode: editorial_workflow
show_preview_links: false

collections:
  - name: 'pages'
    label: 'Pages'
    description: 'Edit the copy of standalone pages on our site.'
    delete: false
    files:
      - file: 'content/pages/code-of-conduct.md'
        label: 'Code of Conduct'
        name: 'code-of-conduct'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'subpage',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'speakers'
    label: 'Speakers'
    identifier_field: name
    label_singular: 'Speaker'
    description: 'Add, edit, or delete speakers here. Speakers here are used on conference pages and the speaker directory.'
    delete: true
    create: true
    folder: 'content/speakers'
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
      - label: 'Pronouns'
        name: 'pronouns'
        widget: 'string'
      - label: 'Role/Company'
        name: 'role'
        widget: 'string'
      - label: 'Social Links'
        name: 'links'
        widget: 'list'
        fields:
          - {
              label: 'Type',
              name: 'type',
              widget: 'select',
              options: ['twitter', 'linkedin', 'github', 'website', 'other'],
            }
          - { label: 'URL', name: 'url', widget: 'string' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'speaker',
        }
      - { label: 'Headshot', name: 'headshot', widget: 'image' }
      - { label: 'Bio', name: 'body', widget: 'text' }

  - name: 'sponsors'
    label: 'Sponsors'
    identifier_field: company
    label_singular: 'Sponsor'
    description: 'Add, edit, or delete sponsors here. Sponsors are shown on the organization page and the conference pages.'
    delete: true
    create: true
    folder: 'content/sponsors'
    fields:
      - label: 'Company'
        name: 'company'
        widget: 'string'
      - label: 'Company URL'
        name: 'company_url'
        widget: 'string'
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - {
          label: 'Organization Sponsor',
          name: 'org_sponsor',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Conference Sponsor',
          name: 'conf_sponsor',
          widget: 'boolean',
          default: false,
        }
      - label: 'Company Text'
        name: 'body'
        widget: 'text'
      - label: 'Years'
        name: 'years'
        widget: 'select'
        multiple: true
        options: ['2018', '2019', '2020']
