backend:
  name: github
  repo: writespeakcode/writespeakcode.com
  branch: production

media_folder: static/images
public_folder: /images

site_url: https://writespeakcode.netlify.com
logo_url: https://raw.githubusercontent.com/WriteSpeakCode/writespeakcode.com/production/src/images/logos/wsc-logo-fullcolor.png

publish_mode: editorial_workflow
show_preview_links: false

collections:
  - name: 'pages'
    label: 'Pages'
    description: 'Edit the copy of standalone pages on our site.'
    delete: false
    files:
      - file: 'content/code-of-conduct.md'
        label: 'Code of Conduct'
        name: 'code-of-conduct'
        fields:
          - label: 'Template Key'
            name: 'templateKey'
            widget: 'hidden'
            default: 'subpage'
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'

  - name: 'speakers'
    label: 'Speakers'
    identifier_field: name
    label_singular: 'Speaker'
    description: 'Add, edit, or delete speakers here. Speakers here are used on conference pages and the speaker directory.'
    delete: true
    create: true
    folder: 'content/speakers'
    extension: 'json'
    fields:
      - label: 'Name'
        name: 'name'
        widget: 'string'
      - label: 'Pronouns'
        name: 'pronouns'
        widget: 'string'
        required: false
      - label: 'Role/Company'
        name: 'role'
        widget: 'string'
        required: false
      - label: 'Social Links'
        name: 'links'
        widget: 'list'
        required: false
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'select'
            options: ['twitter', 'linkedin', 'github', 'website', 'other']
          - label: 'URL'
            name: 'url'
            widget: 'string'
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'speaker'
      - label: 'Headshot'
        name: 'headshot'
        widget: 'image'
        required: false
      - label: 'Bio'
        name: 'bio'
        widget: 'text'
        required: false

  - name: 'sponsors'
    label: 'Sponsors'
    identifier_field: company
    label_singular: 'Sponsor'
    description: 'Add, edit, or delete sponsors here. Sponsors are shown on the organization page and the conference pages.'
    delete: true
    create: true
    folder: 'content/sponsors'
    extension: 'json'
    fields:
      - label: 'Company'
        name: 'company'
        widget: 'string'
        required: true
      - label: 'Company URL'
        name: 'company_url'
        widget: 'string'
        required: false
      - label: 'Logo'
        name: 'logo'
        widget: 'image'
        required: false
      - label: 'Level'
        name: 'level'
        widget: 'select'
        multiple: true
        options: ['platinum', 'gold', 'silver', 'bronze', 'workshop', 'lanyard', 'breakout', 'childcare', 'accessibility', 'headshot', 'local meetup']
        required: false
      - label: 'Organization Sponsor'
        name: 'org_sponsor'
        widget: 'boolean'
        default: false
        required: false
      - label: 'Conference Sponsor'
        name: 'conf_sponsor'
        widget: 'boolean'
        default: false
        required: false
      - label: 'Company Text'
        name: 'company_text'
        widget: 'text'
        required: false
      - label: 'Years'
        name: 'years'
        widget: 'select'
        multiple: true
        options: ['2015', '2016', '2017', '2018', '2019', '2020']
        required: false
