backend:
  name: git-gateway
  repo: writespeakcode/writespeakcode.com

media_folder: static/images
public_folder: /images

site_url: https://writespeakcode.netlify.com
logo_url: https://pbs.twimg.com/profile_images/962066409244172288/-H4OdKh9_400x400.jpg

collections:
  - name: 'pages'
    label: 'Pages'
    description: 'Edit the copy of standalone pages on our site.'
    files:
      - file: 'content/code-of-conduct.md'
        label: 'Code of Conduct'
        name: 'code-of-conduct'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'subpage',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
