name: NPM Audit Fix

on: 
  push:
    branches: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm audit action
      uses: oke-py/npm-audit-action@v1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_assignees: deweydell
        issue_labels: bug
